// THIS FILE IS AUTO GENERATED!
// 2021-04-16T10:53:23.244Z

import { Immutable } from '@offirmo-private/ts-types'

import { Background, BiomeId } from './types'

export const BACKGROUNDS: Immutable<Background[]> = [
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '0d42fb56e9829cec6e9ee8ff44fd.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '103f39beff7ab928b87e398d5675.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '34bd0a8585c95eec4d1cd63967d7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '6a5dc85958c3118a4306a939570e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '881f8c916611abfbd95f5551a5a5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'a0c07cd171d993c368d961057e5e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'd44a2830b970be2c246c631e0ee8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'dd8bd4b68a6eced7a56bd35e87e5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '1e25c89ebb87b6f3aa079f718a7f.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'a7ee862ecf572a0d04273dfc3f49_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'b996c58607994c2abc393f0a.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'dc9602feeb3e0f3138f5eb02ee97.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '15b6fc9952f10e8b9062129811d9_small.jpeg', subfolder: 'to--coastal',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧcoastal,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '86116d35a54dc04ae57093967122.jpeg', subfolder: 'to--coastal',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧcoastal,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '42cddaed0c9f94c528066c383f03_small.jpeg', subfolder: 'to--forest',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '62b662a8f542209d9e8eeecf8fc1.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'd2be5fcaad7d139ce3fe446a29ed.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'daf30c5f9352ee02ed237bd1d30f_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '5ed32e98374b4a81a681.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '74fc671c774d7901c18ed0718f66_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '8c7eec27d60d9c44769fe7d10d6b_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: '9da753553dd59b6e294555fe13a7.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧbarren,
		basename: 'fca97e69b70b59fafc9b73a97f74_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '16e579918b947adcbc7fa220d0f2_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '39f424a70b8ec7c490e6d61c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '521009803dbf91a03b387327a21b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '75aafd31ff0951117802f6fa5111.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '8207aee7a0a76388b791e78eb668.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '9c4906e14aaa0f5b6be1eeff9fe6_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'b240d25fd76081e5d8bdee061daa.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'b3b77e97c470dcbb5ad816469ca4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'e69258e67c986f976b1e8feb37b4_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '13b4e3b5c62b68695f29a2ea0113_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '4e677126f0eb2a374de51b78a78d_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '4efdce0f0eaecb8d2029f89eb673_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '8e7dd27e1ec34137b6b7b67dcd82.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'd74c5c2883a1d07497b8f5e70a30_small.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧbarren,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'feec6df57b3644ce9fbdd6ea.jpeg', subfolder: 'to--coastal',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧcoastal,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'c1f180d387c21ad0ddcf924f9f66.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'c1f180d387c21ad0ddcf924f9f66.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'e08ff46fa5b51e79dbdc.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '221ddd802127405ba205789f.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '5ed081cdc365bce3972a.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '04c21b38371f1150a6776093c118_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '0ca87d771d947bc970c88ae838c5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '12afbb10402f23c4177231e381ab.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '3912d8885aa5d3378ec1bb298743.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '46cfca963b8375a5c79e56848ce7_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '4769bf6f7b31463ae7a272f46f01.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '6b19ca66faeb4659a0e8073547df.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '75f7f56a26e94bfb84baf4b09145_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '7a168c02a230deb3b06c809d960c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '7f2009b6a4ec36b06c9fcc793354.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '804a03876b27c1baa2858de2f1e7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '8accdb9c75d71475a8b97a591f5c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '8b6308a5338131142c4b5d571563.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '8f35a6716dbe50e5bc977dc837d5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '903753899c3c5dd5376758a6983c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'a565a7f13e14e3b5a98cd69b9eb9_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'abec35f3c88765194deb881f1a12.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'b3257224d5e96e5e33877c6b210f_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'b6ebec049792aeeda1a3e195d898.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'd56b78469d651d4cfd3fdf85015b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'd85eb477865a3ba57955024ad1ae.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'e25f03f0edaebd87e0835da5b86d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'e2b9d9510b54f58c69b3d135fe7d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'ea824cda9692a91bfd7b89ac3262.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '58cb3368c3ae050846aa179779d3.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '9618b42652170042307bdec48919.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'cb391f8e1a0743d4108f5431a933.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'd7682cab90d613da33f0bc2eba18.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '9ad51bed2054ad4c2d61956431f2.jpeg', subfolder: 'to--desert',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '99e95dc690722fdb2fa8fa6d4c4e_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '5f98b092eef72dfccbc54e84b92a_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '74e99e623785e3c3d8d0c63d5fd0.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'dff40798bff747ec707f6481b13e.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'f2ab82f8b25c8bd124ff66f0a33b_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'f4bdaf2bbc322c415f544b806eb7.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: '18f791262ff68f12ca7fdcdcf2ad.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcoastal,
		basename: 'e6b6658d57958091b1e326e84626.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '2cbee8c373d548e3ec2de59d784b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3304c777af49ff759c2959b957eb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3dfac28ca56f77068d59d5ba6734_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '5847fe692ca0bee8112a00d63e1a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '683e31188e8f37f06949d87bae33_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '736f3c28401e4a54ad92c277.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '7605d938498576d4e9f7ea2b051d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9134963c231b35f9c61420613045.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9a1e5279633ab05e5885adda3c05.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'c7fc5f75bcb0054ae7e0e1b7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'd20b636e8c54b1083ff7667cf259.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'aa161d0123c0d597f87f7387d689.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'b0001860563468d0fe10418b2852.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'ca9270e90a4bf8dedc6c8b93db6d_small.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '19ba533ed0b90bba4e0af2e92500.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3004d53b22af00b2b8d84a1b168f_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'fe7bc6422b1ff4aa95b9cc3274c5.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0cb89cf5ce087350dccaf97ef37f.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6802e203ca3d71cd1fc6274c6b67_small.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '70a51c616ac2968fd97c4f80736a.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0cf741dff3d717e9ff728a626ad1.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '2e4360dfec99ee2cb1e251746e34.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '63bb67afc00389015650cc16b336.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '852364a52581ee32b1f70ed2bc48_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9711e9007ad7f1c1ca68488b28b1_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'b82d3ddace670ade489250758664.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6f88160e4347ef97b148b29cd5a4_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'ae966700c9e82280f4a7f64ea949_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'd1f1228b56abb4dde9f6573fd0a6.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0e07d815b9b60309cfcb8a4a4781.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3e2d17c7300d29fc166ec3a6451a.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧswamp,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6b5874c4be7e402c4b25db124053.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧswamp,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '029f86133400ef0b1c4cb457d0fb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '05b0639ca1e839fa76dd467d823c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '0bb70c3dbafc15a043a5837ad7c7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '100dca374b64704a01dee9e7671a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '124a67efab85465d7d5b9f971ada.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1bd354ed6ba11b7292a355012420.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1cae27dc9983ccf2da891d63c969.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1f7cad016f687affe7146e84d562.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '252b71148d362d16d2208c9fad01.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '292943f8a0a31d561ba4e87b3aed.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2aa889d34eae5198e4fdb3ddae54.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '321851831852b1f132ed54b60511.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '35d2876f7a912e60752aa3f1ee51.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '38d5a16c1d784758f743e7486389.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '39c1b84d964b921032bce315e0f3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '3b889490c5a7b816312abf2193e1.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4832d112778e73bbd4d8600ae633.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4aa36e6f4495ce9f0c96adca6733.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4c80c6ef3bb439a6dfd4861cb1ae.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4f81ec55f26160be239819302c0b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '56d25fe59e41f16ed69b0644247f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '58a8444af88fe666f723f7a24be0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '58b80314767f2e67b9bf2f78ed37.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '5e24c94edd54c163e7fd6cfc53a0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '66f420c086b2837fb968d9635a17.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '67005ee976c115aa055ebdec4e2a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6ac1e3aa4d034bff7582.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6e171dca8dc5dd40c941147df685.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6ef18e180b91a96125715cb47030.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '722626c1531af177536b355e00a1.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '776eb72e6cbca5032e3e3d12df52.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7b89a866630c9ef444adb538ad2b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7e0d84d95b2b69dce02bd6e0f821.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '80fd8b67ece54a32b7d1a0aa8c5f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '814f13e72d2188842ec4694eba4b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '826f5e8b69e0a7ce8b0aab930d15.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8a90a80dc23c4803c73393a879e4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8c4d8bf227062bf31eac1dfd7f7e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8dcbc57dd287c33b73cabfbcf3ee.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8f2ea8462044ccb131a5cf0bf1a3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8f8fe8f832a11c6c13cdaca907d9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '986489599359062435f3c52c7d47.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '9f0e21b84f20fccb97c21c039fa2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'a22502e4e11c37ea6d32a2176b2f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'a50e79f0492791509e530349b1d9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'aa31b49ee2c56e738eb9a3fb8710.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'abb437f68cdcb33b98d93e65b153.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bd698c1a97211b66f7113a4e207b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bebd7f6a25985bbd5f7aee84815e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bf9ddef4a11586fd52fc3498bf3a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bfa9889dc9b4436931731ceb7105.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c3171f001ce72898eaa15f68025e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c618b5342adb048d1e264b237453.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c73242e83c79e97c976df4079463.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'cb6ee77bf4a8254b781f6320e211.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd3798236e77356350d638347a5a4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd64fbc72385100d045f18a94ebc6.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd7f09649388c43f99828ff11.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'dc12ea57c20641cda36b1396676d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'dc44e6541bb4defa307726d87839.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'e2d8f68a5b0ed79480501f41dc57.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'e38cdedc3dff39cd31dd1ca965f5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'f6ba85aeaef632b93c4b8a21c4f3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'ffc6fe470dd977aa2fc3d91dcfc9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '0c4d89fdc977fa566fb9db09ee17_small.jpeg', subfolder: 'to--desert',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '493a3fcd3c27877996ce40868a90_small.jpeg', subfolder: 'to--desert',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '074d315ed9ef384d57e89daa0ef3_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7cbca3ae8c5abb53b4ad0cfb29e4_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '31f943bd783a9a2d7a1bdfcb7054_small.jpeg', subfolder: 'to--forest--dark',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧdark,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd43ec27c922363ccda7a5cbde783.jpeg', subfolder: 'to--forest--dark',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧdark,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '5233408e5be87f96556dd3f13066_small.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2e81048492b0e39db8c9099bd63d_small.jpeg', subfolder: 'to--forest--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '235ece340abbcad2a4d0be072909.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c3fd3a5468a5181804e3ffd7004f.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'f0e5a479e8e65550c366d2035f9a.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '5a2024620881473d8649861c.jpeg', subfolder: 'to--ghostland',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2c4d40f3314279c6037d3babb1b9.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7554cde6df2ff83427c8d210d7da.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7b3f3fd8b52a642169de9c3fb7cd.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '826f5e8b69e0a7ce8b0aab930d15.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'cb68d182b898aa7d60c4c7071b1e.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8e22b939ff3a8dc1e3855470b2a3.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '0c8e26f62ae14f19bf42e111cab9.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd4d5ac6d4d13c826b83f41bf7812.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '24d94853c8fb88be444f2450cf99_small.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧswamp,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '18d8b86f9df0be24d10a4b2a14b0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '374ecf7b6988abbeef455b2753e1_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '49bf22576c18ac7427816449b88b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '4ed491318ad3bb3df050.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '68feed6a1d6d03d085f4132fa9e7_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '7da1a50af4d139d8268f1a1cbd07.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '88ed54af32e2864ce3e7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '8f77b3a3aa74babda2cf8e202ffb_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '9345716028990f36934c90888e7d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '9a60687d0719c87fc86cf6ffefce_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'c1689a60ebbf8853f41db1362bf8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'eb357c1b4d889435be4df886.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '1d1ddcd4a2487ba89aef1f518a75_small.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '6d55348ac7c5dd56426ecd39b53d_small.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'a86daeb1314cf191fabcb86fdbf3_small.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'f3ecbb12786eaac30e6f4c62fd46.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '146f3300805617e0665e2348c1b3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '1e7c8be4f129e99ee4200b326b63.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '2deaec771e59a43c1825f6da2482.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '46d2cf72103bad2a64bba42f4307.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '603efd9e8c08a1bb7f900f247eb5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '6989e4c3fa3b4dc18fa1366b3f63.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '95a81945c767f9d11d43be9c8383.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9b0cc408526c584a6f62c1180173.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a3c2ba91f1df4d56b4f47f3d93a5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a3e3a4e5871a49681e64.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a58085cacae1c06d04d31c6efb7d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'ab443a57ec11d21fa7b4d4f68b7c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'ae99112f6c50119020d8dfcb82ec.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'b3c0f3ac06737ee2e5b9d34a673f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'b81481f8cea7f4ffbf3d0aba14bb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c6a653e95d6dbfa527f02eb511ad.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c755302a007321aa3e3ca034d5d5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c86ba97ea36cb858b91e415e6ba0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'd47e3dbe44a6e757793c603c39c2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'dd8f7cbc84fd087deba3ae0fa432.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'eb95511326894d87a57ceda3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'fd982bf8dee750dffeae45df2fd5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '15e01f1b5c36a9f3a549f3480cbe.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9ad36942722b78c7da775785ce1d.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c10d14f675a144bfac04a9b18ea1.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '8b64c4bcdfbf61b58b2a61f2fa4c.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧbarren,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'cc12ed24ae02c60c6eb2d5d14fbe_small.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧbarren,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'f6f0abb6adbe54046be68bda5c44_small.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧbarren,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '65c237d28258a3419a2e6b277258_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '813627ac2d1f90c9ebeae159eb0b.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9c6c8ff8834dd3976b8a60ed74fc.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'bde0e1c0c74bc511d7d3b57813b5.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'bf95f3b6c3d5bad1db6dcce24ef3.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '1aa75cdc24d10852b2dd1a59c631_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '3e6f1c6b403a3aced5dc4161.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '7234610f6c6d4dcba42926aa.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '85de17d298593e3dcb45db995af5.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '93b88b102cb9394bdfbb27add7ec.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'd5de94f439366d9a7ae132b8136c_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '5dea2abeb7b06c4897f9ac6caffa_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '7f810aaaf5974cd2bcf969e4.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '82c3f8efa5d8b08f641c857cea69_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '967059e60dbd2fd970213cd542fa.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a808714ea288693e60b392c0f29c_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a9f425001856408b97736548.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '0526b3d94803dd0de03750fd03e7_small.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '85ac6401fa02422e4869c7e0a341_small.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧswamp,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '07925af1e6a1477f839ccd6f9dc8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '0bf643ca383417bf708f1fdb704a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '19709430673e188c9d3c17dcd052_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '1f69f5dea5bfc043ed1ee918dec4_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '33f91dd043bf58674257f95cab38_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '385e0f872a4ac974c34c5692db6d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '42d724866c11d2f4e36384ace621_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '457077e743e81c44b983.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '5412efb32ddb2efe3c99770dc5c6_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '554566f7cf461ae44b41409bc9a5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '575c0ff02f7c2b9f57e8c9f4575b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '6651bd8e43483a4b037eece86fbe_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '7d763ae2dace3211228aef36076d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '85de17d298593e3dcb45db995af5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '9de1dc2fe01270e94247c9f964b0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'add89806d6e917c83759f3de3f8a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'b55e4318dd29f57abc814f08a285_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'bc3921352784d9f42d3de15be236_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'd6f52b4c5b7518c4862e02d029c1_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ddf74a4b8eff4688f8e94001dc9e_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'e44ea03a2eda7b7591a6f26df178_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ebaee4b4c83af50e6cd1a132489c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '70437ecd157ef16a2e499d768088_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ba4a10dbe1ea8e2cfed9761541bc.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'e66bdef1496a9d8a2ec8f6c3552f_small.jpeg', subfolder: 'to--lava',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '18f791262ff68f12ca7fdcdcf2ad_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '5101e49bf631bb46e351f6d0aa37_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '77a4473d2d3344e454b042065a82_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'eec856bf2c395bde04709ffc94dd_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '44cc2d729bec6fac0cefe2d40d8c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '54cb238bfaf83e8e32c539e594e0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '58972f8987fe6091034b52218d04_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '646802f868d2dfcbc78be7239c34.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '6a6957ec08559c1bdf7a6d117c05_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '93b2215c9c1f69b0d265ae44cba0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'dcdef2aa2949dc7568c403ff1d75_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'eabe015b194c9a2a6376c92d7175_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'fec0b55112c8af44f6820e676cc2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'b006aebcef8d2ac88af411bc0615_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'd8594f7b61a2e1b767bc7d51d045_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'e3171d8f2c70f795c1e4e5afabc2.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'ec77edb4fb2241a3bd7dd652.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'f77288c3c0d185ea95fe8e05.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: 'd58020e77b07e2d73871cbdda4d8_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧswamp,
		basename: '9bbdf47ab9fce2b5a0d0d4f46745_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
]

export default BACKGROUNDS
