// THIS FILE IS AUTO GENERATED!
// 2022-03-18T10:34:36.826Z

import { Immutable } from '@offirmo-private/ts-types'

import { Background, BiomeId } from './types'

export const BACKGROUNDS: Immutable<Background[]> = [
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '16e579918b947adcbc7fa220d0f2_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '2e2fbe5cf6c94823e921b977a3e6.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '39f424a70b8ec7c490e6d61c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '75aafd31ff0951117802f6fa5111.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '9c4906e14aaa0f5b6be1eeff9fe6_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'b240d25fd76081e5d8bdee061daa.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'b3b77e97c470dcbb5ad816469ca4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'e69258e67c986f976b1e8feb37b4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '13b4e3b5c62b68695f29a2ea0113_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '4e677126f0eb2a374de51b78a78d_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '4efdce0f0eaecb8d2029f89eb673_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '8e7dd27e1ec34137b6b7b67dcd82.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'd74c5c2883a1d07497b8f5e70a30_small.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'feec6df57b3644ce9fbdd6ea.jpeg', subfolder: 'to--coastal',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'c1f180d387c21ad0ddcf924f9f66.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'c1f180d387c21ad0ddcf924f9f66.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: 'e08ff46fa5b51e79dbdc.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '221ddd802127405ba205789f.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧcave,
		basename: '5ed081cdc365bce3972a.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0f02b0707769bb8f9eb852119e5b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '10721be7579f33fe88735ff3e9f0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '1f7cad016f687affe7146e84d562.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '2cbee8c373d548e3ec2de59d784b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3304c777af49ff759c2959b957eb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3dfac28ca56f77068d59d5ba6734.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '5847fe692ca0bee8112a00d63e1a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '5e24c94edd54c163e7fd6cfc53a0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6749a6d9dea21ad75130c5a5b040.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '683e31188e8f37f06949d87bae33_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6ef18e180b91a96125715cb47030.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '736f3c28401e4a54ad92c277.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '7605d938498576d4e9f7ea2b051d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '8a90a80dc23c4803c73393a879e4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9134963c231b35f9c61420613045.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9a1e5279633ab05e5885adda3c05.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'c3171f001ce72898eaa15f68025e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'c7fc5f75bcb0054ae7e0e1b7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'd20b636e8c54b1083ff7667cf259.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'd7f09649388c43f99828ff11.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'dc12ea57c20641cda36b1396676d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'aa161d0123c0d597f87f7387d689.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'b0001860563468d0fe10418b2852.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'ca9270e90a4bf8dedc6c8b93db6d_small.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '19ba533ed0b90bba4e0af2e92500.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3004d53b22af00b2b8d84a1b168f_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'fe7bc6422b1ff4aa95b9cc3274c5.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0cb89cf5ce087350dccaf97ef37f.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6802e203ca3d71cd1fc6274c6b67_small.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '70a51c616ac2968fd97c4f80736a.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0cf741dff3d717e9ff728a626ad1.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '2e4360dfec99ee2cb1e251746e34.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '63bb67afc00389015650cc16b336.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '75f4b3e4b2d5cb2d2e42de1efa24.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '852364a52581ee32b1f70ed2bc48_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '9711e9007ad7f1c1ca68488b28b1_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'b82d3ddace670ade489250758664.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6f88160e4347ef97b148b29cd5a4_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'ae966700c9e82280f4a7f64ea949_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: 'd1f1228b56abb4dde9f6573fd0a6.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '0e07d815b9b60309cfcb8a4a4781.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '3e2d17c7300d29fc166ec3a6451a.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧdark,
		basename: '6b5874c4be7e402c4b25db124053.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '05b0639ca1e839fa76dd467d823c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '06a27750149744a6f92465ed5656.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '100dca374b64704a01dee9e7671a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '124a67efab85465d7d5b9f971ada.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1bd354ed6ba11b7292a355012420.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1cae27dc9983ccf2da891d63c969.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '1efbc90a982f08c272621c15e4fa.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '252b71148d362d16d2208c9fad01.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '292943f8a0a31d561ba4e87b3aed.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2aa889d34eae5198e4fdb3ddae54.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2fd369e60d1911ab963d1636868c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '321851831852b1f132ed54b60511.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '35d2876f7a912e60752aa3f1ee51.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '39c1b84d964b921032bce315e0f3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4832d112778e73bbd4d8600ae633.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4c80c6ef3bb439a6dfd4861cb1ae.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4f81ec55f26160be239819302c0b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '4fdfb2be7b231942c8c3cb80d1b5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '50bcd6852610d42728a5479e8a97.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '56d25fe59e41f16ed69b0644247f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '58b80314767f2e67b9bf2f78ed37.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6ac1e3aa4d034bff7582.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6e171dca8dc5dd40c941147df685.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '6f7907097a8219174d64cf916a62.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '722626c1531af177536b355e00a1.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '776eb72e6cbca5032e3e3d12df52.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7b89a866630c9ef444adb538ad2b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7e0d84d95b2b69dce02bd6e0f821.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '80fd8b67ece54a32b7d1a0aa8c5f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '814f13e72d2188842ec4694eba4b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '826f5e8b69e0a7ce8b0aab930d15.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8c4d8bf227062bf31eac1dfd7f7e.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8dcbc57dd287c33b73cabfbcf3ee.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8f2ea8462044ccb131a5cf0bf1a3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '986489599359062435f3c52c7d47.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '9f0e21b84f20fccb97c21c039fa2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'a22502e4e11c37ea6d32a2176b2f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'a50e79f0492791509e530349b1d9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'abb437f68cdcb33b98d93e65b153.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'acee4b5a9e8798b3907843a059c2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'ae6a555c1435ace2710627c437fb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bd698c1a97211b66f7113a4e207b.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bf9ddef4a11586fd52fc3498bf3a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'bfa9889dc9b4436931731ceb7105.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c618b5342adb048d1e264b237453.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c66d0df6b441a6b6b1fed6c91ca8.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c73242e83c79e97c976df4079463.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'cb6ee77bf4a8254b781f6320e211.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd3798236e77356350d638347a5a4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd64fbc72385100d045f18a94ebc6.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'dc44e6541bb4defa307726d87839.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'e2d8f68a5b0ed79480501f41dc57.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'e38cdedc3dff39cd31dd1ca965f5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'ffc6fe470dd977aa2fc3d91dcfc9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '0c4d89fdc977fa566fb9db09ee17_small.jpeg', subfolder: 'to--desert',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '493a3fcd3c27877996ce40868a90_small.jpeg', subfolder: 'to--desert',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '074d315ed9ef384d57e89daa0ef3_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7cbca3ae8c5abb53b4ad0cfb29e4_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '31f943bd783a9a2d7a1bdfcb7054_small.jpeg', subfolder: 'to--forest--dark',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧdark,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd43ec27c922363ccda7a5cbde783.jpeg', subfolder: 'to--forest--dark',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧdark,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '5233408e5be87f96556dd3f13066_small.jpeg', subfolder: 'to--forest--fire',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2e81048492b0e39db8c9099bd63d_small.jpeg', subfolder: 'to--forest--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '235ece340abbcad2a4d0be072909.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'c3fd3a5468a5181804e3ffd7004f.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'f0e5a479e8e65550c366d2035f9a.jpeg', subfolder: 'to--forest--spooky',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '5a2024620881473d8649861c.jpeg', subfolder: 'to--ghostland',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '2c4d40f3314279c6037d3babb1b9.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '423ac7ed80a56a2f20a62482a40c.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7554cde6df2ff83427c8d210d7da.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '7b3f3fd8b52a642169de9c3fb7cd.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '826f5e8b69e0a7ce8b0aab930d15.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'cb68d182b898aa7d60c4c7071b1e.jpeg', subfolder: 'to--grassland',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧgrassland,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '8e22b939ff3a8dc1e3855470b2a3.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '0c8e26f62ae14f19bf42e111cab9.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: 'd4d5ac6d4d13c826b83f41bf7812.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧgreen,
		basename: '24d94853c8fb88be444f2450cf99_small.jpeg', subfolder: 'to--swamp',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '18d8b86f9df0be24d10a4b2a14b0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '374ecf7b6988abbeef455b2753e1_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '49bf22576c18ac7427816449b88b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '4ed491318ad3bb3df050.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '68feed6a1d6d03d085f4132fa9e7_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '7da1a50af4d139d8268f1a1cbd07.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '88ed54af32e2864ce3e7.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '8f77b3a3aa74babda2cf8e202ffb_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '9345716028990f36934c90888e7d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '9664e1c575429c10aeabd1ac7cf3_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '9a60687d0719c87fc86cf6ffefce_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'c1689a60ebbf8853f41db1362bf8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'eb357c1b4d889435be4df886.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'f14520a54126ff5636ae1e4869fe.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '6a6d2e51a92553fbb6d7655c5639.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '1d1ddcd4a2487ba89aef1f518a75_small.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '36580c0f6094cb30d9883ba04616.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: '6d55348ac7c5dd56426ecd39b53d_small.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'ae966700c9e82280f4a7f64ea949.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧsnowy,
		basename: 'f3ecbb12786eaac30e6f4c62fd46.jpeg', subfolder: 'to--mountains--snowy',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: '54cb238bfaf83e8e32c539e594e0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: '58972f8987fe6091034b52218d04_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: '646802f868d2dfcbc78be7239c34.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: '93b2215c9c1f69b0d265ae44cba0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'a7cf8a9d2b1407ad76b58f4650ae.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'eabe015b194c9a2a6376c92d7175_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'fec0b55112c8af44f6820e676cc2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'b006aebcef8d2ac88af411bc0615_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'd8594f7b61a2e1b767bc7d51d045_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'e3171d8f2c70f795c1e4e5afabc2.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'ec77edb4fb2241a3bd7dd652.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'f77288c3c0d185ea95fe8e05.jpeg', subfolder: 'to--emerald',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧforestⵧswamp,
		basename: 'd58020e77b07e2d73871cbdda4d8_small.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '146f3300805617e0665e2348c1b3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '46d2cf72103bad2a64bba42f4307.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '5f70c297e0c863253db7f53fa3d9.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '603efd9e8c08a1bb7f900f247eb5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '6989e4c3fa3b4dc18fa1366b3f63.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '95a81945c767f9d11d43be9c8383.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9b0cc408526c584a6f62c1180173.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a3c2ba91f1df4d56b4f47f3d93a5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a3e3a4e5871a49681e64.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a58085cacae1c06d04d31c6efb7d.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'ab443a57ec11d21fa7b4d4f68b7c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'ae99112f6c50119020d8dfcb82ec.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'b3c0f3ac06737ee2e5b9d34a673f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'b81481f8cea7f4ffbf3d0aba14bb.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c6a653e95d6dbfa527f02eb511ad.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'c86ba97ea36cb858b91e415e6ba0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'd47e3dbe44a6e757793c603c39c2.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'e421c13cf65ebe4d262cff337c9a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'eb95511326894d87a57ceda3.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'fd982bf8dee750dffeae45df2fd5.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '15e01f1b5c36a9f3a549f3480cbe.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9ad36942722b78c7da775785ce1d.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '8b64c4bcdfbf61b58b2a61f2fa4c.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'cc12ed24ae02c60c6eb2d5d14fbe.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'f6f0abb6adbe54046be68bda5c44.jpeg', subfolder: 'to--barren',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '65c237d28258a3419a2e6b277258_small.jpeg', subfolder: 'to--forest--autumn',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '4eddaea9b730bb48d18f3c45f3e0.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '67cfc7612f788ff5cedd441052da.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '9c6c8ff8834dd3976b8a60ed74fc.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'f85c0a104f23bbfb4185c2b85086.jpeg', subfolder: 'to--forest--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '85ac6401fa02422e4869c7e0a341_small.jpeg', subfolder: 'to--forest--swamp',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧswamp,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '1aa75cdc24d10852b2dd1a59c631_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '3e6f1c6b403a3aced5dc4161.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '4bfb68d881fd96bd45a9476587ff.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '7052ab9e48fa93b5d99f5041ffbe.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '7234610f6c6d4dcba42926aa.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '85de17d298593e3dcb45db995af5.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '93b88b102cb9394bdfbb27add7ec.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'd5de94f439366d9a7ae132b8136c_small.jpeg', subfolder: 'to--mountain--green',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧgreen,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '5dea2abeb7b06c4897f9ac6caffa_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '7f810aaaf5974cd2bcf969e4.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '82c3f8efa5d8b08f641c857cea69_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '967059e60dbd2fd970213cd542fa.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a808714ea288693e60b392c0f29c_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: 'a9f425001856408b97736548.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧgrassland,
		basename: '0526b3d94803dd0de03750fd03e7_small.jpeg', subfolder: 'to--purple',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '07925af1e6a1477f839ccd6f9dc8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '0bf643ca383417bf708f1fdb704a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '19709430673e188c9d3c17dcd052_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '1f69f5dea5bfc043ed1ee918dec4_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '3792c6056d44b6e451901fc24c61.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '385e0f872a4ac974c34c5692db6d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '42d724866c11d2f4e36384ace621_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '457077e743e81c44b983.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '5412efb32ddb2efe3c99770dc5c6_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '554566f7cf461ae44b41409bc9a5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '575c0ff02f7c2b9f57e8c9f4575b_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '58a8444af88fe666f723f7a24be0.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '6651bd8e43483a4b037eece86fbe_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '7d763ae2dace3211228aef36076d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '8058dcb3241f38c8906a7f136fbc.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '85de17d298593e3dcb45db995af5_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '8ab80ceca1947c509ecd36081853.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '9de1dc2fe01270e94247c9f964b0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ab50a5caf14570ce63909d45b7f4.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ac629ebc92d029e8bf6cf0d0e9ce.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'add89806d6e917c83759f3de3f8a_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'b55e4318dd29f57abc814f08a285_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'd6f52b4c5b7518c4862e02d029c1_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ddf74a4b8eff4688f8e94001dc9e_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'e44ea03a2eda7b7591a6f26df178_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ebaee4b4c83af50e6cd1a132489c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '19bef340209ea432dada0c6028cd.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '70437ecd157ef16a2e499d768088_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'ba4a10dbe1ea8e2cfed9761541bc.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'bc3921352784d9f42d3de15be236_small.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'e66bdef1496a9d8a2ec8f6c3552f_small.jpeg', subfolder: 'to--lava',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '18f791262ff68f12ca7fdcdcf2ad_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '5101e49bf631bb46e351f6d0aa37_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: '77a4473d2d3344e454b042065a82_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧgreen,
		basename: 'eec856bf2c395bde04709ffc94dd_small.jpeg', subfolder: 'to--mountain--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧmountainⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '2dc33717436b05f62f93.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '3c0c4347015f01afa7a13919e87f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '40850e14f9fc893896c0d89a62a0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '5c418038916e3c2ab603f23f80be_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '5df5c4e5c74f081acc9fa3d6ee3d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '6477bf8b4700d3ef66c45bbe0aef_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '6db7dc53380162c5b6807e417811_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '7078bdcffd7e5d8e9fde0ca7e1ef_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '7d4dc9ef74e41943469051227aec_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '7e5a4840746241c7a29f01b2e37c.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '83438e2d3748629536777c4d9399_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '8a94091a9ea130f5e2f99385a937_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '902ebd11a44d8bf68386ed5ca406_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'a4821720d21c695c68f7201044ab.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'a6e7d35812823bb3745b415ed77a.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'b40481e7dc84f89089bcfe7c8e82_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'b4cecc7c9de3330cf2ca07ea1c8f.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'b9c19b03a93645d8493e8769aa6f_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'c7c9adae0f6636993bd588344677.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'c95419de3743cd6322cf0cfd60a2_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'd3edf919b4e3c89f3fa13c491135_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'dea66e3349d0219421799f4e5491_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'e351298c9479b85d10ece0a2b9f8_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'e357f5a3d1c8c507fe1cae1ac8e0_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'f0191b12dbf662d271f4ffb9e02c_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'fa7f04215ab3e4829eb9579d068d_small.jpeg',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '11ed98132988f76f0487c34158cb.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '3e819fcb49a248ef1d9a0044fc26.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '9259a28ec7001a4ffce97da2c6ab.jpeg', subfolder: 'settlements',
		features_settlement: true,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '665a3298004236959f43b70c4cdd.jpeg', subfolder: 'to--forest--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'f621eb261bccfe019893eb184f8b.jpeg', subfolder: 'to--forest--snowy',
		features_settlement: false,
		transitions_to: BiomeId.terrestrialⵧforestⵧsnowy,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '95d779e42db8eebfde24afb207b2_small.jpeg', subfolder: 'to--lava',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '06469242158acd4c77e1905c608e_small.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '08e4b6ee59c34895dfcf6de1bbcf_small.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: '1f7094c65b712c09e907863d38c2.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'bdcc7a7129d8d5cdc301f3c4ff2b_small.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
	{
		biome_id: BiomeId.terrestrialⵧmountainⵧsnowy,
		basename: 'f92181e20d81bb24b2ab389b7dda_small.jpeg', subfolder: 'to--polar',
		features_settlement: false,
		transitions_to: null,
	},
]

export default BACKGROUNDS
